import { expect, test } from '@playwright/test'

test('reference player is a music transport, not Rolar', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/?audio=1')
  const player = page.locator('[data-audio-ref]')
  await player.waitFor()
  await expect(player.locator('[data-audio-open]')).toBeVisible()
  const chip = await player.boundingBox()
  expect(chip, 'chip missing box').toBeTruthy()
  const chipMid = (chip?.x ?? 0) + (chip?.width ?? 0) / 2
  expect(Math.abs(chipMid - 195), 'closed chip not centered on phone').toBeLessThan(12)
  await player.locator('[data-audio-open]').click()
  const card = await player.boundingBox()
  const cardMid = (card?.x ?? 0) + (card?.width ?? 0) / 2
  expect(Math.abs(cardMid - 195), 'open card not centered on phone').toBeLessThan(12)
  await player.locator('[data-audio-close]').click()
  await expect(player.locator('[data-audio-open]')).toBeVisible()
  await expect(player.locator('[data-audio-title]')).toHaveCount(0)
  await player.locator('[data-audio-open]').click()
  await expect(player.locator('[data-audio-kind=sung]')).toBeVisible()
  await expect(player.locator('[data-audio-kind=playback]')).toBeVisible()
  await player.locator('[data-audio-kind=playback]').click()
  await expect(player.locator('[data-audio-kind=playback]')).toHaveAttribute('aria-pressed', 'true')
  await expect(player.locator('[data-audio-title]')).not.toHaveText('')
  await expect(player.locator('[data-audio-artist]')).toBeVisible()
  await expect(player.locator('[data-audio-art]')).toBeVisible()
  await expect(player.locator('[data-icon=play]')).toBeVisible()
  await player.locator('[data-audio-close]').click()
  await expect(player.locator('[data-audio-open]')).toBeVisible()
  await player.locator('[data-audio-open]').click()
  await expect(page.locator('[data-scroll] [data-icon=chevronsDown]')).toBeVisible()
  await expect(page.locator('[data-scroll] [data-icon=play]')).toHaveCount(0)

  await player.locator('[data-audio-play]').click()
  await expect(player.locator('[data-icon=pause]')).toBeVisible()

  const clock = player.locator('[data-audio-clock]')
  await player.locator('[data-audio-skip="1"]').click()
  await expect(clock).not.toHaveText('0:00')
})
