import { expect, test } from '@playwright/test'

test('reference player is a music transport, not Rolar', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/?audio=1')
  const player = page.locator('[data-audio-ref]')
  await player.waitFor()
  await expect(player.locator('[data-audio-open]')).toBeVisible()
  const lead = page.locator('[data-phone-lead]')
  await expect(lead.locator('[data-reading-switch]')).toBeVisible()
  await expect(player).toBeVisible()
  await expect(player.locator('[data-audio-art]')).toHaveCount(0)
  await expect(player.locator('[data-audio-play]')).toHaveCount(0)
  await expect(player.locator('[data-icon=headphones]')).toBeVisible()
  await expect(player.locator('[data-icon=chevronUp]')).toHaveCount(0)
  const phonesBox = await player.locator('[data-audio-open]').boundingBox()
  const readingBox = await lead.locator('[data-reading-switch]').boundingBox()
  expect(phonesBox, 'headphones missing box').toBeTruthy()
  expect(readingBox, 'Cifra/Letra missing box').toBeTruthy()
  expect(
    Math.abs((phonesBox?.y ?? 0) - (readingBox?.y ?? 0)),
    'headphones not on the Cifra/Letra row',
  ).toBeLessThan(12)
  await player.locator('[data-audio-open]').click()
  await expect(lead.locator('[data-reading-switch]')).toBeHidden()
  const card = await player.boundingBox()
  const cardMid = (card?.x ?? 0) + (card?.width ?? 0) / 2
  expect(Math.abs(cardMid - 195), 'open card not centered on phone').toBeLessThan(12)
  await player.locator('[data-audio-close]').click()
  await expect(lead.locator('[data-reading-switch]')).toBeVisible()
  await expect(player.locator('[data-audio-open]')).toBeVisible()
  await expect(player.locator('[data-audio-title]')).toHaveCount(0)
  await player.locator('[data-audio-open]').click()
  await expect(player.locator('[data-audio-kind=sung]')).toBeVisible()
  await expect(player.locator('[data-audio-kind=playback]')).toBeVisible()
  await player.locator('[data-audio-kind=playback]').click()
  await expect(player.locator('[data-audio-kind=playback]')).toHaveAttribute('aria-pressed', 'true')
  await expect(player.locator('[data-audio-title]')).not.toHaveText('')
  await expect(player.locator('[data-audio-artist]')).toBeVisible()
  await expect(player.locator('[data-audio-art]')).toBeVisible()
  await expect(player.locator('[data-icon=play]')).toBeVisible()
  await player.locator('[data-audio-close]').click()
  await expect(player.locator('[data-audio-open]')).toBeVisible()
  await player.locator('[data-audio-open]').click()
  await expect(page.locator('[data-scroll] [data-icon=chevronsDown]')).toBeVisible()
  await expect(page.locator('[data-scroll] [data-icon=play]')).toHaveCount(0)

  await player.locator('[data-audio-play]').click()
  await expect(player.locator('[data-icon=pause]')).toBeVisible()

  const clock = player.locator('[data-audio-clock]')
  await player.locator('[data-audio-skip="1"]').click()
  await expect(clock).not.toHaveText('0:00')

  await player.locator('[data-audio-close]').click()
  await expect(player.locator('[data-icon=headphones]')).toBeVisible()
  await page.locator('[data-cpv-scroll]').click({ position: { x: 180, y: 280 } })
  await expect(page.locator('.cpv-chrome.is-hidden')).toHaveCount(2)
  await expect(page.locator('[data-audio-title]')).toHaveCount(0)
  await expect(page.locator('[data-icon=headphones]')).toBeVisible()
})
