import { expect, test } from '@playwright/test'

test('Só letra hides chords and keeps the lyric', async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 800 })
  await page.goto('/')
  await page.locator('.cpv-chord').first().waitFor()
  await page.locator('[data-reading=letra]').click()
  await expect(page.locator('[data-reading=letra]')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.cpv-chord')).toHaveCount(0)
  await expect(page.locator('.cpv-lyric').first()).toBeVisible()
  await expect(page.locator('.cpv-lyric').first()).not.toHaveText(/^\s*$/)
  const lyrics = (await page.locator('.cpv-lyric').allTextContents()).join('')
  expect(lyrics).not.toMatch(/x\/+/)
  expect(lyrics).not.toMatch(/(^|\s)\/+(\s|$)/)
})

test('host lens=letra opens already in Só letra', async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 800 })
  await page.goto('/?lens=letra')
  await page.locator('.cpv-lyric').first().waitFor()
  await expect(page.locator('[data-reading=letra]')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.cpv-chord')).toHaveCount(0)
})

test('phone Letra is one tap on the dock, not through Mais', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 800 })
  await page.goto('/')
  await page.locator('.cpv-chord').first().waitFor()
  await expect(page.getByRole('dialog', { name: 'Mais controles' })).toHaveCount(0)
  await page.locator('[data-reading=letra]').click()
  await expect(page.locator('[data-reading=letra]')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.cpv-chord')).toHaveCount(0)
  await page.getByRole('button', { name: 'Mais controles' }).click()
  const mais = page.getByRole('dialog', { name: 'Mais controles' })
  await expect(mais).toBeVisible()
  await expect(mais).toContainText('Nashville')
  await expect(mais).toContainText('Comentários de ensaio')
  await expect(mais).not.toContainText('Lentes de leitura')
})

test('Só letra survives changing song in the setlist', async ({ page }) => {
  await page.setViewportSize({ width: 1024, height: 800 })
  await page.goto('/?lista=1&lens=letra')
  await page.locator('[data-setlist-open]').first().waitFor()
  await expect(page.locator('[data-reading=letra]')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.cpv-chord')).toHaveCount(0)
  await page.locator('[data-song-next]').click()
  await expect(page.locator('[data-chart-title]')).toContainText(/Jesus/i)
  await expect(page.locator('[data-reading=letra]')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.cpv-chord')).toHaveCount(0)
})
