import { expect, test } from '@playwright/test'
for (const file of ['notes.gp', 'notes.gp5', 'bends.musicxml', 'bends.gp', 'piano.musicxml']) {
  test(`renders ${file}, switches notation and fits a phone`, async ({ page }, info) => {
    const errors: string[] = []
    page.on('pageerror', e => errors.push(e.message))
    await page.setViewportSize({ width: 900, height: 900 })
    await page.goto(`/notation.html?file=${file}`)
    await expect(page.locator('.cpv-notation-paper svg').first()).toBeVisible({ timeout: 30000 })
    await expect(page.getByRole('status')).toHaveCount(0)
    await expect(page.getByRole('alert')).toHaveCount(0)
    const partitura = page.getByRole('button', { name: 'Partitura', exact: true })
    await partitura.click()
    await expect(partitura).toHaveAttribute('aria-pressed', 'true')
    await page.setViewportSize({ width: 375, height: 850 })
    await expect(page.getByRole('button', { name: 'Zoom do solo', exact: true })).toContainText('Auto (110%)')
    await expect(page.locator('.cpv-notation-paper svg').first()).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)
    const tab = page.getByRole('button', { name: 'TAB', exact: true })
    if (file === 'piano.musicxml') {
      await expect(tab).toBeDisabled()
      await expect(page.getByText('Este arquivo não traz posições nas cordas para exibir TAB.')).toBeVisible()
    }
    if (file.endsWith('.gp') || file.endsWith('.gp5')) await expect(tab).toBeEnabled()
    if (await tab.isEnabled()) { await tab.click(); await expect(tab).toHaveAttribute('aria-pressed', 'true') }
    await page.getByRole('button', { name: 'Zoom do solo', exact: true }).click()
    await page.getByRole('option', { name: '150%', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Zoom do solo', exact: true })).toContainText('150%')
    await page.screenshot({ path: info.outputPath(`${file}-phone.png`), fullPage: true })
    expect(errors).toEqual([])
  })
}
test('edits the selected excerpt and saves the reference', async ({ page }) => {
  await page.goto('/notation.html?edit=1&file=bends.musicxml')
  await expect(page.getByRole('button', { name: 'Faixa', exact: true })).toBeVisible()
  await page.getByLabel('Primeiro compasso').fill('2')
  await page.getByLabel('Último compasso').fill('2')
  await page.getByRole('button', { name: 'Salvar trecho na cifra' }).click()
  await expect(page.locator('body')).toHaveAttribute('data-saved', /track=1 start=2 end=2/)
})

test('uploads an original Guitar Pro file and stores only its reference', async ({ page }) => {
  await page.goto('/notation.html?edit=1')
  await expect(page.getByRole('button', { name: 'Faixa', exact: true })).toBeVisible()
  await page.locator('input[type="file"]').setInputFiles('fixtures/notation/notes.gp')
  await expect(page.getByRole('button', { name: 'Salvar trecho na cifra' })).toBeEnabled()
  await page.getByRole('button', { name: 'Salvar trecho na cifra' }).click()
  await expect(page.locator('body')).toHaveAttribute('data-saved', '{x_titan_score: src="stored/solo.gp" track=1 start=1 end=1 rhythm=extended name="Solo"}')
})

test('Titan renders only the selected bars, without file furniture, and follows theme changes', async ({ page }, info) => {
  await page.goto('/notation.html?file=chords.gp&start=2&end=2&dark=1')
  const system = page.locator('.cpv-notation-system')
  await expect(system.first()).toBeVisible()
  expect(await system.count()).toBe(1)
  await expect(system).toHaveAttribute('data-first-bar', '2')
  await expect(system).toHaveAttribute('data-last-bar', '2')
  await expect(page.locator('.cpv-notation-paper')).not.toContainText(/rendered by|Tuning|Copyright/)
  await expect(page.locator('.cpv-notation-paper .at-chord-diagram')).toHaveCount(0)
  const notation = page.locator('.cpv-notation-paper')
  await expect.poll(async () => (await notation.innerHTML()).toLowerCase()).toContain('#eaecf2')
  await page.screenshot({ path: info.outputPath('titan-solo-dark.png') })
  await page.locator('#toggle-theme').click()
  await expect.poll(async () => (await notation.innerHTML()).toLowerCase()).toContain('#13161d')
  await expect.poll(async () => (await notation.innerHTML()).toLowerCase()).not.toContain('#eaecf2')
  expect(await notation.evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgba(0, 0, 0, 0)')
  await page.screenshot({ path: info.outputPath('titan-solo-light.png') })
})

test('Titan zoom menu follows both themes and supports keyboard and dismissal', async ({ page }, info) => {
  await page.setViewportSize({ width: 375, height: 850 })
  await page.goto('/notation.html?file=notes.gp&dark=1')
  await expect(page.locator('.cpv-notation-paper svg').first()).toBeVisible()
  const trigger = page.getByRole('button', { name: 'Zoom do solo', exact: true })
  const menu = page.getByRole('listbox', { name: 'Zoom do solo' })
  await expect(page.locator('.cpv-external-score select')).toHaveCount(0)
  for (const theme of ['dark', 'light']) {
    await trigger.click()
    await expect(menu).toBeVisible()
    await expect(menu).toHaveCSS('background-color', theme === 'dark' ? 'rgb(23, 27, 36)' : 'rgb(255, 255, 255)')
    await expect(menu).toHaveCSS('color', theme === 'dark' ? 'rgb(234, 236, 242)' : 'rgb(19, 22, 29)')
    await expect(page.getByRole('option', { selected: true })).toHaveCSS('color', theme === 'dark' ? 'rgb(132, 223, 166)' : 'rgb(23, 113, 60)')
    const bounds = await menu.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(375)
    await page.screenshot({ path: info.outputPath(`zoom-${theme}.png`) })
    await page.keyboard.press('Escape')
    await expect(menu).toHaveCount(0)
    await expect(trigger).toBeFocused()
    if (theme === 'dark') await page.locator('#toggle-theme').click()
  }
  await trigger.focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('option', { name: 'Auto (110%)' })).toBeFocused()
  await page.keyboard.press('End')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(trigger).toContainText('150%')
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(page.getByRole('option', { name: '150%', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('Home')
  await page.keyboard.press('Space')
  await expect(trigger).toContainText('Auto (110%)')
  await trigger.click()
  await page.keyboard.press('Tab')
  await expect(menu).toHaveCount(0)
  await trigger.click()
  await page.locator('#toggle-theme').click()
  await expect(menu).toHaveCount(0)
})


test('three TAB rhythms render differently, persist and reset without editing the excerpt', async ({ page }, info) => {
  await page.goto('/notation.html?file=chords.gp')
  const paper = page.locator('.cpv-notation-paper')
  await expect(paper.locator('svg').first()).toBeVisible()
  const initial = await paper.innerHTML()
  const choice = page.getByRole('button', { name: 'Ritmo da TAB', exact: true })
  await choice.click()
  await page.getByRole('option', { name: 'Ritmo na base', exact: true }).click()
  await expect.poll(() => paper.innerHTML()).not.toBe(initial)
  const base = await paper.innerHTML()
  await page.screenshot({ path: info.outputPath('rhythm-base.png'), fullPage: true })
  await page.reload()
  await expect(paper.locator('svg').first()).toBeVisible()
  await expect(choice).toContainText('Ritmo na base')
  expect(await paper.innerHTML()).toBe(base)
  await choice.click()
  await page.getByRole('option', { name: 'Sem ritmo', exact: true }).click()
  await expect.poll(() => paper.innerHTML()).not.toBe(base)
  expect(await paper.innerHTML()).not.toBe(initial)
  await page.screenshot({ path: info.outputPath('rhythm-none.png'), fullPage: true })
  await choice.click()
  await page.getByRole('option', { name: 'Padrão do trecho', exact: true }).click()
  await expect.poll(() => paper.innerHTML()).toBe(initial)
  await page.screenshot({ path: info.outputPath('rhythm-extended.png'), fullPage: true })
  expect(JSON.parse(await page.evaluate(() => localStorage.getItem('cpv:user-preferences') ?? '{}'))).not.toHaveProperty('tabRhythm')
})

test('author chooses the default independently of the saved reading preference', async ({ page }) => {
  await page.goto('/notation.html?edit=1&file=chords.gp')
  await page.evaluate(() => localStorage.setItem('cpv:user-preferences', JSON.stringify({ tabRhythm: 'none' })))
  await page.reload()
  const rhythm = page.getByRole('button', { name: 'Ritmo padrão da TAB', exact: true })
  await expect(rhythm).toBeVisible()
  await rhythm.click()
  await page.getByRole('option', { name: 'Ritmo na base', exact: true }).click()
  await expect(page.locator('.cpv-notation-paper svg').first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ritmo da TAB', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Salvar trecho na cifra' }).click()
  await expect(page.locator('body')).toHaveAttribute('data-saved', /rhythm=base name="Solo"}/)
  expect(JSON.parse(await page.evaluate(() => localStorage.getItem('cpv:user-preferences') ?? '{}')).tabRhythm).toBe('none')
})

for (const size of [{ width: 1280, height: 900 }, { width: 375, height: 812 }]) {
  for (const theme of ['light', 'dark']) {
    test(`import layout and interval ${size.width} ${theme}`, async ({ page }, info) => {
      await page.setViewportSize(size)
      await page.goto(`/notation.html?edit=1&file=chords.gp${theme === 'dark' ? '&dark=1' : ''}`)
      const dialog = page.getByRole('dialog')
      await expect(dialog.locator('.cpv-notation-paper svg').first()).toBeVisible()
      await expect(dialog.locator('select')).toHaveCount(0)
      const first = page.getByRole('spinbutton', { name: 'Primeiro compasso' })
      const last = page.getByRole('spinbutton', { name: 'Último compasso' })
      await last.fill('9999')
      await last.press('Tab')
      await expect(last).toHaveValue('5')
      await first.fill('-3')
      await first.press('Tab')
      await expect(first).toHaveValue('1')
      const start = page.getByRole('slider', { name: 'Início do intervalo' })
      await start.focus()
      await start.press('ArrowRight')
      await expect(first).toHaveValue('2')
      const end = page.getByRole('slider', { name: 'Fim do intervalo' })
      await end.focus()
      await end.press('ArrowLeft')
      await expect(last).toHaveValue('4')
      await expect(dialog.locator('.cpv-import-score-actions')).toContainText('3 compassos selecionados')
      const rhythm = page.getByRole('button', { name: 'Ritmo padrão da TAB', exact: true })
      await rhythm.click()
      await expect(page.getByRole('listbox', { name: 'Ritmo padrão da TAB' })).toBeVisible()
      const menuBounds = await page.getByRole('listbox', { name: 'Ritmo padrão da TAB' }).boundingBox()
      const bodyBounds = await dialog.locator('.cpv-import-score-body').boundingBox()
      expect(menuBounds!.y).toBeGreaterThanOrEqual(bodyBounds!.y)
      expect(menuBounds!.y + menuBounds!.height).toBeLessThanOrEqual(bodyBounds!.y + bodyBounds!.height)
      await page.screenshot({ path: info.outputPath(`import-${size.width}-${theme}-menu.png`) })
      await page.getByRole('option', { name: 'Ritmo na base', exact: true }).click()
      await expect(dialog).toBeVisible()
      expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
      expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(size.width)
      await dialog.locator('.cpv-import-score-body').evaluate(el => { el.scrollTop = 0 })
      await page.screenshot({ path: info.outputPath(`import-${size.width}-${theme}.png`) })
      const save = page.getByRole('button', { name: 'Salvar trecho na cifra' })
      const box = await save.boundingBox()
      expect(box!.y + box!.height).toBeLessThanOrEqual(size.height)
      await save.click()
      await expect(page.locator('body')).toHaveAttribute('data-saved', /start=2 end=4 rhythm=base name="Solo"}/)
    })
  }
}

test('new upload and a single-bar file remain usable on a small phone', async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 640 })
  await page.goto('/notation.html?edit=1&new=1')
  await expect(page.getByRole('button', { name: 'Escolher arquivo', exact: true })).toBeVisible()
  await page.getByRole('dialog').evaluate(el => Promise.all(el.getAnimations().map(a => a.finished)))
  await page.screenshot({ path: info.outputPath('import-empty-phone.png') })
  await page.locator('input[type="file"]').setInputFiles('fixtures/notation/notes.gp')
  await expect(page.getByRole('spinbutton', { name: 'Último compasso' })).toHaveValue('1')
  await expect(page.getByRole('slider', { name: 'Início do intervalo' })).toBeDisabled()
  await expect(page.getByRole('slider', { name: 'Fim do intervalo' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Salvar trecho na cifra' })).toBeEnabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await expect(page.getByRole('button', { name: 'Ritmo padrão da TAB', exact: true })).toContainText('Ritmo na base')
  await page.getByRole('button', { name: 'Salvar trecho na cifra' }).click()
  await expect(page.locator('body')).toHaveAttribute('data-saved', '{x_titan_score: src="stored/solo.gp" track=1 start=1 end=1 rhythm=base name="Solo"}')
})


test('range handles drag independently and cannot cross', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/notation.html?edit=1&file=chords.gp')
  const first = page.getByRole('spinbutton', { name: 'Primeiro compasso' })
  const last = page.getByRole('spinbutton', { name: 'Último compasso' })
  await expect(first).toHaveValue('1')
  const slider = page.getByRole('slider', { name: 'Início do intervalo' })
  const box = (await slider.boundingBox())!
  const at = (bar: number) => box.x + 12 + (box.width - 24) * (bar - 1) / 4
  await page.mouse.move(at(1), box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(at(3), box.y + box.height / 2, { steps: 12 })
  await page.mouse.up()
  await expect(first).toHaveValue('3')
  await page.mouse.move(at(5), box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(at(1), box.y + box.height / 2, { steps: 12 })
  await page.mouse.up()
  await expect(last).toHaveValue('3')
  await first.fill('5')
  await first.press('Tab')
  await expect(first).toHaveValue('3')
  await page.getByRole('button', { name: 'Selecionar tudo' }).click()
  await expect(first).toHaveValue('1')
  await expect(last).toHaveValue('5')
})

for (const width of [375, 1280]) {
  test(`notation controls share one compact row at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/notation.html?file=chords.gp')
    await expect(page.locator('.cpv-notation-paper svg').first()).toBeVisible()
    const controls = ['TAB', 'Partitura', 'Ritmo da TAB', 'Zoom do solo'].map(name => page.getByRole('button', { name, exact: true }))
    const boxes = await Promise.all(controls.map(control => control.boundingBox()))
    for (const box of boxes) {
      expect(Math.abs(box!.y - boxes[0]!.y)).toBeLessThan(1)
      expect(box!.height).toBe(boxes[0]!.height)
      expect(box!.x + box!.width).toBeLessThanOrEqual(width)
    }
    const details = page.locator('.cpv-score-controls .cpv-score-choice-value')
    for (const detail of await details.all()) {
      if (width < 640) await expect(detail).toBeHidden()
      else await expect(detail).toBeVisible()
    }
    await controls[3]!.click()
    await expect(page.getByRole('option', { name: /Auto \(/ })).toBeVisible()
    const menu = (await page.getByRole('listbox', { name: 'Zoom do solo' }).boundingBox())!
    expect(menu.x).toBeGreaterThanOrEqual(0)
    expect(menu.x + menu.width).toBeLessThanOrEqual(width)
    await page.screenshot({ path: info.outputPath(`compact-controls-${width}.png`) })
  })
}
