import { readFileSync } from 'node:fs'
import { expect, test } from '@playwright/test'

const fixture = readFileSync('fixtures/013-ele-vive-em-mim-partitura.cho', 'utf8')

for (const width of [390, 1280]) test(`Guitar Pro stays below the introduction after upload, save and reading (${width}px)`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.addInitScript(() => localStorage.setItem('titan-chordpro:editSeen', '1'))
  await page.goto('/demo-insertion.html?editMode=persisted')
  await page.locator('[data-edit]').click()
  if (await page.locator('[data-mode-content]').count()) await page.locator('[data-mode-content]').click()
  await page.locator('[data-source]').click()
  await page.getByRole('textbox', { name: 'Fonte ChordPro' }).fill(fixture)
  await page.getByRole('button', { name: 'Fechar painel de source' }).click()
  const at = fixture.split('\n').findIndex(l => l.startsWith('Por [G]onde'))
  await page.locator(`[data-insert-at="${at}"]`).click()
  await page.getByRole('button', { name: 'Guitar Pro / MusicXML', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Solo de Guitar Pro ou MusicXML' })
  await dialog.locator('input[type="file"]').setInputFiles('fixtures/notation/notes.gp')
  await expect(dialog.locator('.titan-chordpro-notation-paper svg').first()).toBeVisible()
  await dialog.getByRole('button', { name: 'Salvar trecho na cifra' }).click()
  await expect(dialog).toHaveCount(0)
  await page.locator('[data-source]').click()
  const saved = await page.getByRole('textbox', { name: 'Fonte ChordPro' }).inputValue()
  expect(saved.split('\n')[at]).toMatch(/^\{x_titan_score:/)
  expect(saved.replace(/^\{x_titan_score:.*\}\n\n/m, '')).toBe(fixture)
  await page.getByRole('button', { name: 'Fechar painel de source' }).click()
  await page.locator('[data-save]').click()
  await page.locator('[data-read]').click()
  const solo = page.locator('[data-external-score]')
  await expect(solo.locator('.titan-chordpro-notation-paper svg').first()).toBeVisible()
  const row = solo.locator('xpath=ancestor::*[@data-block]')
  const previous = row.locator('xpath=preceding-sibling::*[@data-block][1]')
  await expect(previous).toContainText('G/B')
  const next = row.locator('xpath=following-sibling::*[@data-block][1]')
  await expect(next).toContainText('onde')
  expect((await row.boundingBox())!.y).toBeGreaterThan((await previous.boundingBox())!.y)
})

for (const width of [390, 1280]) for (const releaseOnly of [false, true]) test(`dragging Guitar Pro lands after the introduction (${width}px, final position on ${releaseOnly ? 'release' : 'move'})`, async ({ page }) => {
  await page.setViewportSize({ width, height: 700 })
  await page.addInitScript(() => localStorage.setItem('titan-chordpro:editSeen', '1'))
  await page.goto('/demo-insertion.html?editMode=persisted')
  await page.locator('[data-edit]').click()
  if (await page.locator('[data-mode-content]').count()) await page.locator('[data-mode-content]').click()
  await page.locator('[data-source]').click()
  await page.route('**/fixtures/notation/notes.gp', route => route.fulfill({ path: 'fixtures/notation/notes.gp', contentType: 'application/octet-stream' }))
  const solo = '{x_titan_score: src="/fixtures/notation/notes.gp" track=1 start=1 end=1}'
  await page.getByRole('textbox', { name: 'Fonte ChordPro' }).fill(`${solo}\n\n${fixture}`)
  await page.getByRole('button', { name: 'Fechar painel de source' }).click()
  await expect(page.locator('[data-external-score] .titan-chordpro-notation-paper svg').first()).toBeVisible()
  const grip = page.locator('[data-grip="0"]')
  await grip.scrollIntoViewIfNeeded()
  const start = (await grip.boundingBox())!
  await page.mouse.move(start.x + start.width / 2, start.y + 20)
  await page.mouse.down()
  await page.mouse.move(start.x + start.width / 2, start.y + 40)
  const verse = page.locator('[data-block]').filter({ hasText: 'onde' }).first()
  await verse.scrollIntoViewIfNeeded()
  const target = (await verse.boundingBox())!
  if (releaseOnly) {
    const intro = (await verse.locator('xpath=preceding-sibling::*[@data-block][1]').boundingBox())!
    await page.evaluate(y => window.dispatchEvent(new PointerEvent('pointermove', { clientY: y, pointerType: 'mouse' })), intro.y + 2)
    // A release event can arrive without a move at its final coordinates.
    await page.evaluate(({ x, y }) => window.dispatchEvent(new PointerEvent('pointerup', { clientX: x, clientY: y, pointerType: 'mouse' })), { x: start.x + start.width / 2, y: target.y + 3 })
  } else await page.mouse.move(start.x + start.width / 2, target.y + 3)
  await page.mouse.up()
  await page.locator('[data-source]').click()
  const saved = await page.getByRole('textbox', { name: 'Fonte ChordPro' }).inputValue()
  expect(saved.indexOf(solo)).toBeGreaterThan(saved.indexOf('[G]x///'))
  expect(saved.indexOf(solo)).toBeLessThan(saved.indexOf('Por [G]onde'))
  await page.getByRole('button', { name: 'Fechar painel de source' }).click()
  await page.locator('[data-save]').click()
  await page.locator('[data-read]').click()
  const row = page.locator('[data-external-score]').locator('xpath=ancestor::*[@data-block]')
  await expect(row.locator('.titan-chordpro-notation-paper svg').first()).toBeVisible()
  await expect(row.locator('xpath=preceding-sibling::*[@data-block][1]')).toContainText('G/B')
  await expect(row.locator('xpath=following-sibling::*[@data-block][1]')).toContainText('onde')
})

test('insert below the introduction, duplicate and move the copy to a later verse', async ({ page }) => {
  const chart = readFileSync('fixtures/sda/h031-jesus-tu-es-a-minha-vida.cho', 'utf8')
  await page.setViewportSize({ width: 1280, height: 700 })
  await page.addInitScript(() => localStorage.setItem('titan-chordpro:editSeen', '1'))
  await page.goto('/demo-insertion.html?editMode=persisted')
  await page.locator('[data-edit]').click()
  if (await page.locator('[data-mode-content]').count()) await page.locator('[data-mode-content]').click()
  await page.locator('[data-source]').click()
  await page.getByRole('textbox', { name: 'Fonte ChordPro' }).fill(chart)
  await page.getByRole('button', { name: 'Fechar painel de source' }).click()
  const at = chart.split('\n').findIndex(line => line.startsWith('Je[G]sus'))
  await page.locator(`[data-insert-at="${at}"]`).click()
  await page.getByRole('button', { name: 'Guitar Pro / MusicXML', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Solo de Guitar Pro ou MusicXML' })
  await dialog.locator('input[type="file"]').setInputFiles('fixtures/notation/notes.gp')
  await expect(dialog.locator('.titan-chordpro-notation-paper svg').first()).toBeVisible()
  await dialog.getByRole('button', { name: 'Salvar trecho na cifra' }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('[data-external-score]')).toHaveCount(1)
  const original = page.locator('[data-external-score]').first().locator('xpath=ancestor::*[@data-block]')
  await expect(original.locator('xpath=preceding-sibling::*[@data-block][1]')).toContainText('x///')
  await expect(original.locator('xpath=following-sibling::*[@data-block][1]')).toContainText('Tu És a minha')
  const originalBi = Number(await original.getAttribute('data-block'))
  await page.locator(`[data-grip="${originalBi}"]`).dispatchEvent('keydown', { key: 'Enter' })
  await page.locator('[data-duplicate]').click()
  await expect(page.locator('[data-external-score]')).toHaveCount(2)
  const copy = page.locator('[data-external-score]').nth(1).locator('xpath=ancestor::*[@data-block]')
  const copyBi = Number(await copy.getAttribute('data-block'))
  const grip = page.locator(`[data-grip="${copyBi}"]`)
  await grip.scrollIntoViewIfNeeded()
  const from = (await grip.boundingBox())!
  const targetBlock = page.locator('[data-block]').filter({ hasText: 'canto' }).first()
  await page.mouse.move(from.x + from.width / 2, from.y + 15)
  await page.mouse.down()
  await page.mouse.move(from.x + from.width / 2, from.y + 35)
  await targetBlock.scrollIntoViewIfNeeded()
  const to = (await targetBlock.boundingBox())!
  await page.mouse.move(from.x + from.width / 2, to.y + 2)
  await page.mouse.up()
  await page.locator('[data-source]').click()
  const result = await page.getByRole('textbox', { name: 'Fonte ChordPro' }).inputValue()
  const refs = [...result.matchAll(/^\{x_titan_score:.*\}$/gm)]
  expect(refs).toHaveLength(2)
  expect(refs[0]!.index).toBeGreaterThan(result.indexOf('[G]x///'))
  expect(refs[0]!.index).toBeLessThan(result.indexOf('Je[G]sus'))
  expect(refs[1]!.index).toBeGreaterThan(result.indexOf('{c:(INTERLÚDIO - SOLO GUITARRA E PADDING)}'))
})
