export type {
  BlockMarks,
  BlockMusic,
  CapoChordPair,
  CapoLegend,
  ChartBlock,
  ChartBlockBody,
  ChartRow,
  ChartSeg,
  ChordProLine,
  ChordProSection,
  ChordProView,
  Lens,
  LineSpan,
  ParseIssue,
  SectionKind,
  SongBlockExtras,
  TabStave,
  TabToken,
  ThemeId,
  ViewerAction,
  ViewerController,
  ViewerState,
} from './types'

export type { ChartStore } from './storage'
export {
  STORE_KEYS,
  browserStore,
  memoryStore,
  overlayKey,
  readJson as readStoredJson,
  writeJson as writeStoredJson,
} from './storage'

export { parse, normalizeSource, setKey, transpose } from './parse'
export { renderHtml, isParseFatal } from './render-html'
export { listThemes, resolveTheme, assertTheme, themeCssVars, accentVars, listAccents, THEME_VARS, cssVarsString } from './themes'
export type { AccentId, AccentProp } from './themes'
export { buildChoFilename, buildPdfFilename, buildSljaFilename } from './filenames'
export { lyricsForSlides, lyricsText, exportLyrics } from './lyrics-for-slides'
export type { SlideSourceLine, ChartLyrics } from './lyrics-for-slides'
export { exportCho, patchMeta } from './export-cho'
export { calcScrollSpeed, adjustScrollSpeed, viewerMulStep } from './scroll'
export {
  ANCHOR_RAMP,
  ANCHOR_RATIO,
  anchorPx,
  pxAtScroll,
  scrollAtPx,
  barsAtPx,
  beatsPerBar,
  buildTimeline,
  clockOf,
  contentOrigin,
  etaSec,
  formatEta,
  durationFromYoutubeHtml,
  formatDurationFromSec,
  hasSongDuration,
  isPlayedLine,
  lineBeats,
  marksPerBeat,
  maskDurationMmSs,
  normalizeDurationMmSs,
  playheadAtScroll,
  pxAtBars,
  runSec,
  scrollAtPlayhead,
  sheetBpm,
  songDurationSec,
} from './timeline'
export type { Timeline, TimelineBlock, TimelineOpts, TimelineSeg } from './timeline'
export { createViewerController } from './controller'
export { createSourceSession } from './source-session'
export type { SourceSession, SourceChangeReason } from './source-session'
export {
  layoutChart,
  layoutChartFull,
  buildTab,
  editTypeScale,
  typeScale,
  maxPlainChars,
  markTight,
} from './layout'
export type { ChartLayout, LayoutOpts } from './layout'
export { readingWords } from './reading-words'
export type { ReadingCell, ReadingWord } from './reading-words'
export {
  absorbInto,
  absorbedOp,
  applyOps,
  checkUpdate,
  diffOps,
  hasRun,
  hashText,
  isTuneOp,
  lcsHunks,
  opCtxNote,
  opLabel,
  overlaid,
  strumReviewFromOp,
  diffStrumPattern,
  slotsLookSame,
  tuneText,
} from './overlay'
export type {
  ApplyResult,
  Hunk,
  Overlay,
  OverlayOp,
  ReadingCtx,
  ResolvedOp,
  StrumReview,
  StrumSlotMark,
  Suggestion,
  SuggestionStatus,
  TextOp,
  TuneOp,
  UpdateItem,
  UpdatePlan,
} from './overlay'
export {
  addChord,
  blockLabel,
  blockSpan,
  copyHarmony,
  deleteBlock,
  duplicateBlock,
  groupAfter,
  hideBlock,
  insertAt,
  insertBlock,
  insertImage,
  insertSnippet,
  lastChordName,
  markCtx,
  moveBlock,
  moveChord,
  pasteHarmony,
  playedColumns,
  removeChord,
  renameChord,
  rowJoin,
  rowParts,
  setBlockCapo,
  setComment,
  setLyric,
  shiftBlock,
  shiftLabel,
  toggleBlockDual,
  unhideBlock,
  writeMarks,
} from './block-edit'
export type {
  BlockSpan,
  BlockWrite,
  ChordRef,
  Harmony,
  HarmonyRow,
  InsertKind,
  MarkCtx,
  PlayedCol,
  RowParts,
} from './block-edit'
export {
  BEATS,
  DEFAULT_META,
  DEMO,
  DURS,
  DUR_OF,
  NAMES,
  PT,
  STR_LBL,
  STR_MIDI,
  beatsOf,
  beatsPerBar as scoreBeatsPerBar,
  keyOf,
  layout as scoreLayout,
  parseScore,
  serialize as serializeScore,
  tabOf,
  toTab,
} from './score'
export type { Dur, LayoutItem, ParsedScore, ScoreMeta, ScoreNote, TabPos } from './score'
export { lintSource } from './lint'
export type { LintResult } from './lint'
export { transposeToken, usesFlats, keyIndex, keyRootOf, nashvilleToken, semitoneDelta, signedSemitoneDelta, formatToneShift, transposeTextChords } from './transpose'
export { looksLikeOnSong, normalizeOnSong } from './onsong'
export {
  applyCcStrumChoice,
  applyCifraClubEnrich,
  chartBody,
  convert,
  detect,
  detectKeyRewrite,
  enrichMetaFromCifraClubHtml,
  fromCifraClubHtml,
  fromOnSong,
  fromPlain,
  hostOk,
  inferWrittenKey,
  isChord,
  isChordLine,
  looksLikeCifraClubHtml,
  META_KEYS,
  MISSING_LABEL,
  missingOf,
  proposeCifraClubEnrich,
  readMeta,
  readStrumPatterns,
  rewriteToKey,
  SUPPORTED_HOSTS,
  titleFromUrl,
  toPlain,
  trazerCcStrumChoice,
  writeMeta,
  writeStrumPatterns,
  youtubeEmbedUrl,
  youtubeWatchUrl,
} from './import-chordpro'
export type {
  CcStrumChoice,
  ChartMeta,
  CifraClubPage,
  EnrichConflict,
  EnrichProposal,
  EnrichStrumConflict,
  EnrichYoutube,
  ImportFormat,
  ImportResult,
  KeyRewriteOffer,
  MetaKey,
  RewriteToKeyResult,
} from './import-chordpro'
export {
  formatXStrumSet,
  metaFromStrumSet,
  parseXStrumSet,
} from './strum-multi'
export type { StrumPatternSet } from './strum-multi'
export {
  beatsInMeter,
  decodeStrumPat,
  densityFromGrid,
  dirAtOffset,
  emptyPattern,
  emptySlot,
  encodeStrumPat,
  findAnchorIndex,
  formatXStrum,
  gridFromDensity,
  hasStrumAnchor,
  inferSixEightPulse,
  isCompleteStrumPattern,
  isEmptySlot,
  isLegalStrumPattern,
  listSlotChoices,
  meterFromTimeSignature,
  oppositeDir,
  parseXStrum,
  patternFromCc,
  repairStrumPattern,
  requiredDir,
  resizePattern,
  setSlot,
  setSlotCascading,
  slotEquals,
  slotFromCcCode,
  slotsFromCcPattern,
} from './strum'
export type {
  EmptyPatternOpts,
  SixEightPulse,
  StrumContact,
  StrumDensity,
  StrumDir,
  StrumEssence,
  StrumPattern,
  StrumSlot,
} from './strum'
export { applyStrumPreset, draftStrumPreset, listStrumPresets } from './strum-presets'
export type { SaveStrumPresetPayload, StrumPreset } from './strum-presets'
